version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - directory: "/"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
  - directory: "/MCStructs-bedrock-forms"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
  - directory: "/MCStructs-bedrock-nbt"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
  - directory: "/MCStructs-bedrock-text"
    package-ecosystem: "gradle"
    schedule:
      interval: "daily"
